### ISSUE TITLE
Default password?

### ISSUE THREAD

**Issue by fa72bd53** [Staffjoy/suite#50]
Hello!

This is very definitely a dumb question, but: what is the default password, if any, of the user/s created via the user.txt file? 
I saw in the code it might be "staffjoydev", but that seems not to work.

Any help is greatly appreciated.
Thank you :)

**Comment by philipithomas** [comment]
Hey - it should be `staffjoydev`. Can you confirm that the users made it into the database? My suspicion is that the users were not created, and that is why the login is failing. (i.e., password is right, but user account doesn't exist)

**Comment by fa72bd53** [comment]
Thank you for the quick reply! And sorry, should have tested that before posting, had been a long day...
Anyway the user seems to be there, even with a pw:
mysql> select id, username, email, sudo, confirmed, password_hash from users;
```
+----+----------+--------------------+------+-----------+--------------------------------------------------------------------+
| id | username | email              | sudo | confirmed | password_hash                                                      |
+----+----------+--------------------+------+-----------+--------------------------------------------------------------------+
|  1 | NULL     | vuser@resuv.suerv  |    0 |         0 | pbkdf2:sha1:1000$bRTd1FUG$aa305f [...] 67d0f2 |
|  2 | NULL     | feynman@7bridg.es  |    0 |         0 | NULL                                                               |
```
(together with 6 or so other testusers (I guess); edit: omitted some part of the hash just because it felt wrong ;)

I copied the whole repository anew (this time used the email suggested in the readme.md), make dev, install nodejs6, make dev again, halt, up,  make dev-server and now:
mysql> select id, username, email, sudo, confirmed, password_hash from users;
```
+----+----------+--------------------+------+-----------+---------------+
| id | username | email              | sudo | confirmed | password_hash |
+----+----------+--------------------+------+-----------+---------------+
|  1 | NULL     | lenny@staffjoy.com |    1 |         0 | NULL          |
|  2 | sudo     | sudo@staffjoy.com  |    1 |         1 | NULL          |
+----+----------+--------------------+------+-----------+---------------+
```
Login still not possible :(

Edit2: I should add that I then destroyed and set up the second (lenny/sudo) vagrant again, just to be sure; same result. [still have the very first one (vuser/feynman) though, if there is still hope for it]

**Comment by philipithomas** [comment]
It looks like those users do not have passwords set 🤷‍♂ 

I unfortunately no longer have time to maintain this code, nor do I remember the specifics of how it installs these fixtures. 

I suggest that you use the Flask command line to query these users, then directly set the password. 

If you find any fixes - feel free to submit a PR!
