### ISSUE TITLE
[Question] Recurring shifts not being converted into real shifts, time off requests

### ISSUE THREAD

**Issue by 0x41mmarVM** [Staffjoy/suite#51]
Hello,
Thank you for open sourcing this. I appreciate this is no longer being maintained, but I imagine this is a bit of a noob question.

After wrangling a bit with upgrading packages, Python behaviour changes, and so on, I managed to get the dev environment up and running. But now as I try to use it, I have two issues that do not appear to be errors:

1. I create recurring shifts for roles or employees, but these never seem to appear on the schedules. They're there when I list shifts, but the schedule is clean, no shifts are added unless I add them manually. No errors are thrown anywhere, and the recurring shifts are there in the database. At what point are they supposed to be created? There are many references in the code to a schedule being unpublished/published, but nothing in the interface seems to refer to this.

2. It does not appear that users can request time-off from their own accounts. Managers are able to create time off requests and accept them in their own accounts, but users don't seem to be able to. Is this actually not supported? or am I missing something?

The tutorial videos may have helped, but it seems they've been taken off Youtube. If there's any alternative place for me to find them, I'd appreciate a pointer.

Many thanks for your help,.

**Comment by philipithomas** [comment]
Hey there - it's been a few years since I've looked at this code. But, I'll try answering:

>    I create recurring shifts for roles or employees, but these never seem to appear on the schedules. They're there when I list shifts, but the schedule is clean, no shifts are added unless I add them manually. No errors are thrown anywhere, and the recurring shifts are there in the database. At what point are they supposed to be created? There are many references in the code to a schedule being unpublished/published, but nothing in the interface seems to refer to this.

It seems to me that the `cron` process isn't set up: https://github.com/philipithomas/staffjoy-cron

(You don't need that specific code - but, you need to hit the internal cron endpoint on a recurring basis)

>    It does not appear that users can request time-off from their own accounts. Managers are able to create time off requests and accept them in their own accounts, but users don't seem to be able to. Is this actually not supported? or am I missing something?

They should be able to. I suspect this is also related to the cron setup - because the `week` hasn't been initiated in the database yet by the cron process.

**Comment by 0x41mmarVM** [comment]
The cron endpoint was being hit frequently and regularly, but when I double checked following your response, I noticed it was getting a 404, so that makes sense.

Thanks a lot for your help!
